# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://localhost/miniproj/index.php")
    self.driver.set_window_size(697, 720)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("annapops")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("annapops1")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "propertiesDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Search Properties").click()
    self.driver.find_element(By.ID, "state").click()
    dropdown = self.driver.find_element(By.ID, "state")
    dropdown.find_element(By.XPATH, "//option[. = 'Kerala']").click()
    self.driver.find_element(By.ID, "district").click()
    dropdown = self.driver.find_element(By.ID, "district")
    dropdown.find_element(By.XPATH, "//option[. = 'Kochi']").click()
    self.driver.find_element(By.ID, "place").click()
    dropdown = self.driver.find_element(By.ID, "place")
    dropdown.find_element(By.XPATH, "//option[. = 'Ernakulam']").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
