# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestViewproperty():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_viewproperty(self):
    self.driver.get("http://localhost/")
    self.driver.set_window_size(697, 720)
    self.driver.find_element(By.LINK_TEXT, "miniproj/").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("annapops")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("annapops1")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "propertiesDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "View Property").click()
    self.driver.find_element(By.CSS_SELECTOR, ".property-item:nth-child(4) a").click()
    self.driver.find_element(By.NAME, "intrestBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
  
